#!/usr/bin/env python3
"""Mirror the learned Session hygiene rules into an always-on Cursor rule.

Claude loads corpus/CLAUDE.learned.md through ~/.claude/CLAUDE.md, but
Cursor only reads ~/.cursor/rules/*.mdc, so a rule that lives only in the
learned file never reaches a Cursor session. This writes the
"# Session hygiene" section of that file, verbatim, into
~/.cursor/rules/session-hygiene.mdc with alwaysApply: true.

The target is a generated real file, not a symlink: Cursor needs the
frontmatter, and the source file carries other sections too. Safe to
rerun. --remove deletes a file this script generated (an engine-only
install drops the learned rules, so the mirror goes with them). A real
file that was not generated here is left alone and reported.
"""
import os
import sys

REPO_DIR = os.path.dirname(os.path.abspath(__file__))
LEARNED_PATH = os.path.join(REPO_DIR, "corpus", "CLAUDE.learned.md")
RULE_NAME = "session-hygiene.mdc"
RULE_PATH = os.path.expanduser(os.path.join("~", ".cursor", "rules", RULE_NAME))
SECTION_HEADING = "# Session hygiene"
GENERATED_MARKER = (
    "<!-- generated by catstack install.sh from corpus/CLAUDE.learned.md;"
    " edit the source and rerun ./install.sh -->"
)
FRONTMATTER = (
    "---\n"
    "description: Suggest /clear or a fresh session on an unrelated pivot;"
    " park abandoned work before switching\n"
    "alwaysApply: true\n"
    "---\n"
)


def extract_section(text, heading=SECTION_HEADING):
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if line.startswith(heading):
            start = index
            break
    if start is None:
        raise SystemExit(f"fail    {LEARNED_PATH}: no '{heading}' section to mirror")
    end = len(lines)
    for index in range(start + 1, len(lines)):
        if lines[index].startswith("# "):
            end = index
            break
    body = "\n".join(lines[start:end]).strip()
    if not any(line.startswith("- ") for line in body.splitlines()):
        raise SystemExit(f"fail    {LEARNED_PATH}: '{heading}' section has no rules")
    return body


def render(section):
    return FRONTMATTER + GENERATED_MARKER + "\n\n" + section + "\n"


def read_existing(path):
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def remove():
    if os.path.islink(RULE_PATH):
        print(f"skip    {RULE_NAME} (symlink, not generated by catstack; left alone)")
        return 0
    if not os.path.exists(RULE_PATH):
        print(f"ok      {RULE_NAME} (absent; engine-only drops learned rules)")
        return 0
    if GENERATED_MARKER not in read_existing(RULE_PATH):
        print(f"skip    {RULE_NAME} (real file not generated by catstack; left alone)")
        return 0
    os.remove(RULE_PATH)
    print(f"remove  {RULE_NAME} (engine-only drops learned rules)")
    return 0


def install():
    content = render(extract_section(read_existing(LEARNED_PATH)))
    os.makedirs(os.path.dirname(RULE_PATH), exist_ok=True)
    if os.path.islink(RULE_PATH):
        print(f"skip    {RULE_NAME} (symlink already exists; remove it to let install.sh generate)")
        return 0
    action = "write"
    if os.path.exists(RULE_PATH):
        existing = read_existing(RULE_PATH)
        if existing == content:
            print(f"ok      {RULE_NAME} (already up to date)")
            return 0
        if GENERATED_MARKER not in existing:
            print(f"skip    {RULE_NAME} (real file not generated by catstack; remove it to let install.sh generate)")
            return 0
        action = "update"
    with open(RULE_PATH, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"{action:<7} {RULE_NAME} (from corpus/CLAUDE.learned.md '{SECTION_HEADING}')")
    return 0


def main(argv):
    if "--remove" in argv:
        return remove()
    return install()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
